### ISSUE TITLE
Mail Access Chekker error

### ISSUE THREAD

**Issue by ticamilica9** [henry-richard7/Mail-Access-Bruter#1]
Hello!

I tried to use your script and all I get is proxy error growing and nothing more...I tried also to contact you on the channel but useless. Could you please let me know what could be the issue why the Checker is not starting to check the combos and only get proxy error? With respect!!!
![error](https://github.com/henry-richard7/Mail-Access-Bruter/assets/162847731/90483316-0ce5-4b8d-8d7c-5c0b707dd428)

**Comment by henry-richard7** [comment]
Hi,
I am no longer maintaining this script.
